// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Preferences {
    "last_directory": string | null;
    "recent_directories": string[] | null;
    "theme": string;
    "language": string;
    "sidebar_visible": boolean;
    "show_decorations": boolean;
    "read_only_wheel_zoom": boolean;
}
