// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface DialogOptions {
    "title": string;
    "kind": string;
    "okLabel": string;
    "cancelLabel": string;
}
