// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as drawing$0 from "../drawing/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as preferences$0 from "../preferences/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Ask(message: string, options: $models.DialogOptions): $CancellablePromise<boolean> {
    return $Call.ByID(2167884787, message, options);
}

export function CancelClose(): $CancellablePromise<void> {
    return $Call.ByID(498648696);
}

export function CreateNewFile(directory: string, fileName: string): $CancellablePromise<string> {
    return $Call.ByID(741602754, directory, fileName);
}

export function CreateNewFolder(directory: string, folderName: string): $CancellablePromise<string> {
    return $Call.ByID(73572896, directory, folderName);
}

export function DeleteFile(filePath: string): $CancellablePromise<void> {
    return $Call.ByID(1531072447, filePath);
}

export function DeleteFolder(folderPath: string): $CancellablePromise<void> {
    return $Call.ByID(734262137, folderPath);
}

/**
 * ExportFile supports browser-originated Excalidraw, PNG, SVG and library exports.
 * Its destination is always selected in a native dialog, never supplied by JS.
 */
export function ExportFile(name: string, encoded: string): $CancellablePromise<void> {
    return $Call.ByID(2066601314, name, encoded);
}

export function ForceCloseApp(): $CancellablePromise<void> {
    return $Call.ByID(1131070470);
}

export function GetFileTree(directory: string): $CancellablePromise<drawing$0.Node[] | null> {
    return $Call.ByID(1792952652, directory);
}

export function GetPreferences(): $CancellablePromise<preferences$0.Preferences> {
    return $Call.ByID(3098855848);
}

export function HashFileContent(filePath: string): $CancellablePromise<string> {
    return $Call.ByID(2137866497, filePath);
}

export function ListExcalidrawFiles(directory: string): $CancellablePromise<drawing$0.File[] | null> {
    return $Call.ByID(2452821589, directory);
}

export function Message(message: string, options: $models.DialogOptions): $CancellablePromise<void> {
    return $Call.ByID(1204887341, message, options);
}

export function PendingOpenFiles(): $CancellablePromise<string[] | null> {
    return $Call.ByID(1278972440);
}

export function ReadFile(filePath: string): $CancellablePromise<string> {
    return $Call.ByID(1476160192, filePath);
}

export function ReadFileWithHash(filePath: string): $CancellablePromise<drawing$0.Content> {
    return $Call.ByID(2000402408, filePath);
}

export function RenameFile(oldPath: string, newName: string): $CancellablePromise<string> {
    return $Call.ByID(2575966910, oldPath, newName);
}

export function RenameFolder(oldPath: string, newName: string): $CancellablePromise<string> {
    return $Call.ByID(1303466540, oldPath, newName);
}

export function SaveFile(filePath: string, content: string): $CancellablePromise<string> {
    return $Call.ByID(3041238501, filePath, content);
}

export function SaveFileAs(content: string): $CancellablePromise<string | null> {
    return $Call.ByID(1291198605, content);
}

export function SavePreferences(prefs: preferences$0.Preferences): $CancellablePromise<void> {
    return $Call.ByID(3458273687, prefs);
}

export function SelectDirectory(): $CancellablePromise<string | null> {
    return $Call.ByID(1674382173);
}

export function SetDecorations(visible: boolean): $CancellablePromise<void> {
    return $Call.ByID(2366511473, visible);
}

export function SetMenuVisible(visible: boolean): $CancellablePromise<void> {
    return $Call.ByID(1583938325, visible);
}

export function WatchDirectory(directory: string): $CancellablePromise<void> {
    return $Call.ByID(909216688, directory);
}
