// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Content {
    "content": string;
    "content_hash": string;
}

export interface File {
    "name": string;
    "path": string;
    "modified": boolean;
}

export interface Node {
    "name": string;
    "path": string;
    "is_directory": boolean;
    "modified": boolean;
    "children": Node[] | null;
}
